### ISSUE TITLE
App Crash after it starts

### ISSUE THREAD

**Issue by arttuladhar** [e2thed/mobile-class#1]
02-21 14:17:52.871    1901-1901/seng.contactsviewer I/art﹕ Not late-enabling -Xcheck:jni (already on)
02-21 14:17:52.970    1901-1901/seng.contactsviewer D/Database operations﹕ Database created
02-21 14:17:53.090    1901-1901/seng.contactsviewer D/Database operations﹕ Table created
02-21 14:17:53.176    1901-1901/seng.contactsviewer D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
02-21 14:17:53.176    1901-1901/seng.contactsviewer E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: seng.contactsviewer, PID: 1901
    java.lang.RuntimeException: Unable to start activity ComponentInfo{seng.contactsviewer/seng.contactsviewer.ListContactsActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
            at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
            at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
            at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
            at seng.contactsviewer.ListContactsActivity.onCreate(ListContactsActivity.java:51)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by e2thed** [comment]
This looks like a result of having an empty database. I commented out the "seed" information for testing, but did not get to the part where I add a contact when none exist.

To get it running, we should add the "seed" until I/we get to the null list scenario.

**Comment by arttuladhar** [comment]
could you push your change so that it wont break while trying to fire up.

**Comment by e2thed** [comment]
This sounds like it works now
